### ISSUE TITLE
König implementieren

### ISSUE THREAD

**Issue by SonjaRass** [SE2-Gruppe-E-Royal-Dog/GruppenPhaseAndroid#19]
- [König darf nur von einem König geschlagen werden ] 

- [ König darf nur mit Karten von 1-7 bewegt werden]

**Comment by d2rainer** [comment]
Regeln für Überholen implementiert
Weitere Sonderfunktionen noch offen

**Comment by d2rainer** [comment]
Sonderfunktionen für Überholen und Schlagen implementiert.
Move - Sonderfunktion noch offen.

**Comment by d2rainer** [comment]
Fertig implementiert
