### ISSUE TITLE
Narr implementieren

### ISSUE THREAD

**Issue by SonjaRass** [SE2-Gruppe-E-Royal-Dog/GruppenPhaseAndroid#22]
- [ zieht der Narr ins Ziel, darf er bis zu 2 Punkte verfallen lassen]

**Comment by SonjaRass** [comment]
- [ Rangfolge beachten]

**Comment by d2rainer** [comment]
Regeln für Überholen implementiert
Weitere Sonderfunktionen noch offen

**Comment by d2rainer** [comment]
Sonderfunktionen für Überholen und Schlagen implementiert.
Move - Sonderfunktion noch offen.

**Comment by d2rainer** [comment]
Fertig implementiert
