### ISSUE TITLE
Ein Spielzug

### ISSUE THREAD

**Issue by SonjaRass** [SE2-Gruppe-E-Royal-Dog/GruppenPhaseAndroid#25]
- [ Karte ausspielen] 
- 

- [ Figur bewegen] 

implementiert in #23 Kartenset und #26Spielfigur

**Comment by d2rainer** [comment]
Regular-Move Methode und rauß schmeißen implementiert. 
Zieleinfahrt und Input von Karten noch offen.

**Comment by d2rainer** [comment]
Move fertig für: aus StartingArea rauß fahren, ins Ziel einfahren, normaler Spielzug, Bedingungen für Überholen, rauswerfen
