### ISSUE TITLE
Spielfiguren implementieren

### ISSUE THREAD

**Issue by SonjaRass** [SE2-Gruppe-E-Royal-Dog/GruppenPhaseAndroid#26]
Spielfiguren inkl. Grafik

Spielzüge implementieren

Spieler anlegen

**Comment by SonjaRass** [comment]
UI F
Figuren
Event Listener

**Comment by d2rainer** [comment]
Move Methode implementiert
UI und Event Listener noch offen

**Comment by d2rainer** [comment]
UI fertig, Überholen und move fertig
zusätzliche Sonderfunktionen folgen im nächsten Sprint

**Comment by d2rainer** [comment]
Grundstruktur für Figurtypen angelegt
Überholen und Schlagen im Prinzip für alle 4 Figuren fertig - inkl. Sonderfunktionen
Ausnahmen für Zielfelder fehlen noch
Move Sonderregeln für alle 4 Figuren noch offen - hängt tlw. noch von nicht implementierten Karten ab.
