### ISSUE TITLE
Als Spieler möchte ich die Wurmlöcher verschieben können

### ISSUE THREAD

**Issue by d2rainer** [SE2-Gruppe-E-Royal-Dog/GruppenPhaseAndroid#34]
Schummelfunktion

**Comment by SonjaRass** [comment]
auslesen des Licht Sensors wurde implementiert
Server erhält eine Nachricht, wenn LichtSensor Wert 0 ist

//TODO
Server Meldung an Klasse cheat_light (inkl. erstellen) retour melden
Random mit Wurmlöchern implementieren

**Comment by SonjaRass** [comment]
Wurmlöcher wurden implementiert
Referenzen zwischen den Wurmlöchern wurde implementiert - Wechsel zwischen 1 und 2 und 3 und 4 (vor und zurück)
Random Verschiebung der Wurmlöcher auf dem Spielbrett wurde implementiert

TODO - GameManager muss Nachricht vom Server erhalten und die switchMethode aufrufen.. GameManager wird erst implementiert

**Comment by SonjaRass** [comment]
Game Manager wurde implementiert
