### ISSUE TITLE
Als Spieler will ich meinen Spielzug manipulieren können - Schummeln

### ISSUE THREAD

**Issue by claudialei** [SE2-Gruppe-E-Royal-Dog/GruppenPhaseAndroid#40]
Schummelfunktin
wenn der Spieler während seines Zuges das Handy nach Links oder Rechts Kippt, fährt er plus/minus 1 Feld
Möglich 1x alle 5 Runden

**Comment by SonjaRass** [comment]
Klasse und Überprüfungen wurden angelegt... Koppelung mit GameManager folgt

**Comment by SonjaRass** [comment]
added CheatModifier in GameManger and Playingfield inkl. Tests
