### ISSUE TITLE
Test für Move Methode - Überholen

### ISSUE THREAD

**Issue by SonjaRass** [SE2-Gruppe-E-Royal-Dog/GruppenPhaseAndroid#80]

**Comment by d2rainer** [comment]
Check für Überholen getestet - Methoden umgeschrieben; funktioniert

**Comment by d2rainer** [comment]
Noch offen: GreenCard testen

**Comment by SonjaRass** [comment]
in progress - check green card fehlt noch

**Comment by d2rainer** [comment]
Green Card getestet
