### ISSUE TITLE
Als Spielfeld will ich eine gegnerische Figur schlagen

### ISSUE THREAD

**Issue by SonjaRass** [SE2-Gruppe-E-Royal-Dog/GruppenPhaseAndroid#9]
- [ Figur auf neues Feld setzen] 
- -Interkation mit Netzwerk

- [ gegnerische Figur ins passende Startfeld verschieben] 
- - Interaktion mit Netzwerk

**Comment by d2rainer** [comment]
In Move-Methode implementiert inkl. GetRightStartingAreaField
